name: Gthub-Sprb-1

on:
  push:
    paths:
      - 'gthub-sprb-1/**'
  pull_request:
    paths:
      - 'gthub-sprb-1/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gthub-sprb-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and Test
        run: mvn clean install

      - name: Package
        run: mvn package -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gthub-sprb-1-jar
          path: gthub-sprb-1/target/*.jar
